### ISSUE TITLE
Android Basics: Get data from the Internet

### ISSUE THREAD

**Issue by petarsrzentic** [google-developer-training/android-basics-kotlin-mars-photos-app#13]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

<img width="1394" alt="Screenshot 2021-04-07 at 14 23 30" src="https://user-images.githubusercontent.com/59149136/113865919-faa1aa00-97ac-11eb-8dcd-d019f17f6686.png">

val listResult = MarsApi.retrofitService.getProperties()
 _status.value = listResult

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by gitgrimbo** [comment]
Duplicates
#58
#55
#50
#38
#31
#29
#21
#19
#14
#13

**Comment by osuleymanova** [comment]
@petarsrzentic 
Thank you for reaching out to us. The issue is fixed and published:

https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#5
