### ISSUE TITLE
Android Basics: Get data from the Internet

### ISSUE THREAD

**Issue by willow19** [google-developer-training/android-basics-kotlin-mars-photos-app#14]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#5**

**Task 6: Connecting to the internet, Step: 5**

**In the code snippet:
val listResult = MarsApi.retrofitService.getProperties()
is mentioned instead of
val listResult = MarsApi.retrofitService.getPhotos()
**

**Steps to reproduce?**
1. Go to the URL
2. Click on Task 6 (Connecting to Internet)
3. Scroll to Step 5

**Versions**
_Android Studio version:_ NA
_API version of the emulator:_ NA
 

**Additional information**
![Screenshot from 2021-04-08 10-50-53](https://user-images.githubusercontent.com/9603417/113972643-93413400-9858-11eb-909e-4aa8350c24c7.png)

**Comment by gitgrimbo** [comment]
Duplicates
#58
#55
#50
#38
#31
#29
#21
#19
#14
#13

**Comment by osuleymanova** [comment]
@willow19 
Thank you for reaching out to us. The issue is fixed and published:

https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#5
