### ISSUE TITLE
Android Basics: Get data from the Internet

### ISSUE THREAD

**Issue by 2dnas** [google-developer-training/android-basics-kotlin-mars-photos-app#21]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#5**

**Task 6. Connecting to the Internet,   Step 5 of the Call the web service in OverviewViewModel**

**In the step 5 where we assign the result we just received from the backend server to the _status.value in the 
example code there is a mistake. There should be val listResult = MarsApi.retrofitService.getPhotos() instead val listResult = MarsApi.retrofitService.getProperties()**

**Steps to reproduce?**
1. Go to the link and task 6 scroll down till the end 
2. I think the method name is incorrect in code example 
![error2](https://user-images.githubusercontent.com/44274932/115869571-1b295f80-a44f-11eb-8ad8-5e49a0faa9ec.PNG)

**Comment by gitgrimbo** [comment]
Duplicates
#58
#55
#50
#38
#31
#29
#21
#19
#14
#13

**Comment by osuleymanova** [comment]
@2dnas  
Thank you for reaching out to us. The issue is fixed and published:

https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#5
