### ISSUE TITLE
Android Basics: Get data from the Internet

### ISSUE THREAD

**Issue by iownthegame** [google-developer-training/android-basics-kotlin-mars-photos-app#29]
---
name: Android Basics Unit 4 issue
about: Report problems with the Android Basics Unit 4 codelabs
title: 'Android Basics Unit 4 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#5

**In which task and step of the codelab can this issue be found?**
Get data from the internet >> 6. Connecting to the Internet

**Describe the problem**
`val listResult = MarsApi.retrofitService.getProperties()` -> should be 
`val listResult = MarsApi.retrofitService.getPhotos()`

See screenshot below:
![image](https://user-images.githubusercontent.com/1487369/117686412-6e3e3900-b1e9-11eb-95ec-7fbf20efb0d0.png)

**Comment by gitgrimbo** [comment]
Duplicates
#58
#55
#50
#38
#31
#29
#21
#19
#14
#13

**Comment by osuleymanova** [comment]
@iownthegame 
Thank you for reaching out to us. The issue is fixed and published:

https://developer.android.com/codelabs/basic-android-kotlin-training-getting-data-internet?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-4-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-getting-data-internet#5
